### ISSUE TITLE
Problem with run.sh

### ISSUE THREAD

**Issue by WildEchoes** [mrakotosaon/dse-meshing#8]
I have a problem when I run run.sh. I don't know why it happens. Looking forward to your help.
Environment： python=3.6   numpy=1.19.2  trimesh=3.20.2   tensorflow=1.15.0

step: 0/78
step: 50/78
Traceback (most recent call last):
  File "triangle_selection/select.py", line 4, in <module>
    import numpy as np
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/site-packages/numpy/core/__init__.py", line 101, in <module>
    from . import _internal
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/site-packages/numpy/core/_internal.py", line 10, in <module>
    import platform
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/subprocess.py", line 137, in <module>
    import select
  File "/home/yy/reconstruction/dse-meshing/triangle_selection/select.py", line 7, in <module>
    import trimesh
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/site-packages/trimesh/__init__.py", line 15, in <module>
    from .base import Trimesh
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/site-packages/trimesh/base.py", line 8, in <module>
    from . import ray
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/site-packages/trimesh/ray/__init__.py", line 1, in <module>
    from .import ray_triangle
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/site-packages/trimesh/ray/ray_triangle.py", line 7, in <module>
    from .ray_util import contains_points
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/site-packages/trimesh/ray/ray_util.py", line 3, in <module>
    from .. import util
  File "/home/yy/anaconda3/envs/dse-meshing/lib/python3.6/site-packages/trimesh/util.py", line 67, in <module>
    TOL_ZERO = np.finfo(np.float64).resolution * 100
AttributeError: module 'numpy' has no attribute 'finfo'

**Comment by WildEchoes** [comment]
I find the key problem is the version of the package. 
# Recommend Version 
numpy==1.16.0   
trimesh==3.9.0
scikit-learn==0.24.2
scipy==1.5.2 

Hope it can help you!
